// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ping struct {
	_tab flatbuffers.Table
}

func GetRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ping{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Ping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ping) ClientTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ping) MutateClientTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func PingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PingAddClientTime(builder *flatbuffers.Builder, clientTime int64) {
	builder.PrependInt64Slot(0, clientTime, 0)
}
func PingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
