// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SHU
{

using global::System;
using global::FlatBuffers;

public enum PacketID : ushort
{
 Ping = 1,
 SyncTime = 2,
};


}
