// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SHU.FlatBuffers.Ping
{

using global::System;
using global::FlatBuffers;

public struct SyncTime : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SyncTime GetRootAsSyncTime(ByteBuffer _bb) { return GetRootAsSyncTime(_bb, new SyncTime()); }
  public static SyncTime GetRootAsSyncTime(ByteBuffer _bb, SyncTime obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool SyncTimeBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "sync"); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SyncTime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerTime { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<SyncTime> CreateSyncTime(FlatBufferBuilder builder,
      long serverTime = 0) {
    builder.StartObject(1);
    SyncTime.AddServerTime(builder, serverTime);
    return SyncTime.EndSyncTime(builder);
  }

  public static void StartSyncTime(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddServerTime(FlatBufferBuilder builder, long serverTime) { builder.AddLong(0, serverTime, 0); }
  public static Offset<SyncTime> EndSyncTime(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SyncTime>(o);
  }
  public static void FinishSyncTimeBuffer(FlatBufferBuilder builder, Offset<SyncTime> offset) { builder.Finish(offset.Value, "sync"); }
};


}
